import { Product, CartItem, User } from './types'

export const mockProducts: Product[] = [
    {
        id: '1',
        name: 'iPhone 12 Pro 128GB',
        price: 7500000,
        originalPrice: 12000000,
        discount: 38,
        condition: 'Like New',
        image: 'https://bimg.akulaku.net/goods/spu/1589e502d4194a8381e504b52c7630a84379.jpeg',
        images: [
            'https://bimg.akulaku.net/goods/spu/1589e502d4194a8381e504b52c7630a84379.jpeg',
            'https://images.tokopedia.net/img/cache/700/product-1/2020/10/23/53614/53614_c0c9f9b8-0be1-45e0-a7db-c3b1bb41a7f5_700_700',
        ],
        rating: 4.8,
        reviewCount: 156,
        seller: {
            id: 's1',
            name: 'TechStore Jakarta',
            avatar: 'https://placehold.co/100x100',
            rating: 4.9,
            responseTime: '< 1 hour',
            totalSales: 1250,
            verified: true
        },
        isPremium: true,
        category: 'Electronics',
        description: 'Kondisi mulus seperti baru, fullset box, charger original, no minus. Battery health 92%, layar mulus tanpa goresan. Sudah termasuk case dan tempered glass.',
        location: 'Jakarta Selatan',
        stock: 1
    },
    {
        id: '2',
        name: 'Nike Air Max 270 React',
        price: 850000,
        originalPrice: 2100000,
        discount: 60,
        condition: 'Good',
        image: 'https://images.tokopedia.net/img/cache/700/VqbcmM/2023/11/18/b3dfa805-cfed-4079-a542-0312a5be6808.jpg',
        images: [
            'https://images.tokopedia.net/img/cache/700/VqbcmM/2023/11/18/b3dfa805-cfed-4079-a542-0312a5be6808.jpg',
        ],
        rating: 4.6,
        reviewCount: 89,
        seller: {
            id: 's2',
            name: 'SneakerHub',
            avatar: 'https://placehold.co/100x100',
            rating: 4.7,
            responseTime: '< 2 hours',
            totalSales: 890,
            verified: true
        },
        isPremium: true,
        category: 'Fashion',
        description: 'Size 42, pemakaian normal, box dan tag lengkap',
        location: 'Bandung',
        stock: 1
    },
    {
        id: '3',
        name: 'MacBook Pro 2019 13"',
        price: 12500000,
        originalPrice: 24000000,
        discount: 48,
        condition: 'Like New',
        image: 'https://i.ebayimg.com/00/s/MTE5N1gxNDU4/z/Ko4AAOSw-F1jN1x0/$_12.JPG?set_id=880000500F',
        images: [
            'https://i.ebayimg.com/00/s/MTE5N1gxNDU4/z/Ko4AAOSw-F1jN1x0/$_12.JPG?set_id=880000500F',
        ],
        rating: 4.9,
        reviewCount: 203,
        seller: {
            id: 's3',
            name: 'LaptopPremium',
            avatar: 'https://placehold.co/100x100',
            rating: 4.9,
            responseTime: '< 30 mins',
            totalSales: 2100,
            verified: true
        },
        isPremium: true,
        category: 'Electronics',
        description: 'i5 8GB RAM 256GB SSD, battery health 95%, no dent',
        location: 'Surabaya',
        stock: 1
    },
    {
        id: '4',
        name: 'IKEA Sofa 3 Seater',
        price: 2500000,
        originalPrice: 5500000,
        discount: 55,
        condition: 'Good',
        image: 'https://d2xjmi1k71iy2m.cloudfront.net/dairyfarm/id/images/494/0949429_PE799735_S4.jpg',
        images: [
            'https://d2xjmi1k71iy2m.cloudfront.net/dairyfarm/id/images/494/0949429_PE799735_S4.jpg',
        ],
        rating: 4.5,
        reviewCount: 67,
        seller: {
            id: 's4',
            name: 'FurnitureCo',
            avatar: 'https://placehold.co/100x100',
            rating: 4.6,
            responseTime: '< 3 hours',
            totalSales: 340,
            verified: false
        },
        isPremium: false,
        category: 'Furniture',
        description: 'Bahan fabric, warna grey, kondisi bersih terawat',
        location: 'Tangerang',
        stock: 1
    },
    {
        id: '5',
        name: 'Canon EOS M50 Kit',
        price: 6800000,
        originalPrice: 10500000,
        discount: 35,
        condition: 'Like New',
        image: 'https://jakartacamera.com/wp-content/uploads/2020/10/237505195alt5.jpg',
        images: [
            'https://jakartacamera.com/wp-content/uploads/2020/10/237505195alt5.jpg',
        ],
        rating: 4.7,
        reviewCount: 124,
        seller: {
            id: 's5',
            name: 'CameraShop',
            avatar: 'https://placehold.co/100x100',
            rating: 4.8,
            responseTime: '< 1 hour',
            totalSales: 560,
            verified: true
        },
        isPremium: true,
        category: 'Electronics',
        description: 'Shutter count rendah, lengkap dengan lensa kit 15-45mm',
        location: 'Jakarta Pusat',
        stock: 1
    },
    {
        id: '6',
        name: 'Adidas Ultraboost 21',
        price: 1200000,
        originalPrice: 2800000,
        discount: 57,
        condition: 'Good',
        image: 'https://img.ncrsport.com/img/storage/large/s23863-1.jpg',
        images: [
            'https://img.ncrsport.com/img/storage/large/s23863-1.jpg',
        ],
        rating: 4.4,
        reviewCount: 78,
        seller: {
            id: 's6',
            name: 'RunnersPro',
            avatar: 'https://placehold.co/100x100',
            rating: 4.5,
            responseTime: '< 2 hours',
            totalSales: 430,
            verified: false
        },
        isPremium: false,
        category: 'Fashion',
        description: 'Size 43, kondisi bagus, masih empuk',
        location: 'Bekasi',
        stock: 1
    },
    {
        id: '7',
        name: 'Harry Potter Complete Set',
        price: 650000,
        originalPrice: 1200000,
        discount: 46,
        condition: 'Good',
        image: 'https://images-cdn.ubuy.co.id/6545af6414631025c0516eb5-1-st-edition-harry-potter-full-book-set.jpg',
        images: [
            'https://images-cdn.ubuy.co.id/6545af6414631025c0516eb5-1-st-edition-harry-potter-full-book-set.jpg',
        ],
        rating: 4.8,
        reviewCount: 145,
        seller: {
            id: 's7',
            name: 'BookLover',
            avatar: 'https://placehold.co/100x100',
            rating: 4.7,
            responseTime: '< 4 hours',
            totalSales: 280,
            verified: false
        },
        isPremium: false,
        category: 'Books',
        description: '7 books, English version, paperback, kondisi buku bagus',
        location: 'Yogyakarta',
        stock: 1
    },
    {
        id: '8',
        name: 'PlayStation 4 Pro 1TB',
        price: 3500000,
        originalPrice: 6500000,
        discount: 46,
        condition: 'Good',
        image: 'https://www.static-src.com/wcsstore/Indraprastha/images/catalog/full//catalog-image/98/MTA-143627506/no_brand_ps4_pro_1tb_original_full01_ndzbxbbp.jpg',
        images: [
            'https://www.static-src.com/wcsstore/Indraprastha/images/catalog/full//catalog-image/98/MTA-143627506/no_brand_ps4_pro_1tb_original_full01_ndzbxbbp.jpg',
        ],
        rating: 4.6,
        reviewCount: 189,
        seller: {
            id: 's8',
            name: 'GamingHub',
            avatar: 'https://placehold.co/100x100',
            rating: 4.8,
            responseTime: '< 1 hour',
            totalSales: 780,
            verified: true
        },
        isPremium: true,
        category: 'Electronics',
        description: 'Termasuk 2 stik, 5 game, kondisi normal lancar',
        location: 'Semarang',
        stock: 1
    },
    {
        id: '9',
        name: 'Pakaian Wanita Salur Maroon',
        price: 43200,
        originalPrice: 80000,
        discount: 46,
        condition: 'Good',
        image: 'https://www.static-src.com/wcsstore/Indraprastha/images/catalog/full//116/MTA-63559898/brd-44261_kaos-salur-wanita-lengan-panjang_full01.jpg',
        images: [
            'https://www.static-src.com/wcsstore/Indraprastha/images/catalog/full//116/MTA-63559898/brd-44261_kaos-salur-wanita-lengan-panjang_full01.jpg',
        ],
        rating: 4.2,
        reviewCount: 15,
        seller: {
            id: 's9',
            name: 'KostumMuslimah',
            avatar: 'https://placehold.co/100x100',
            rating: 4.8,
            responseTime: '< 1 hour',
            totalSales: 150,
            verified: false
        },
        isPremium: false,
        category: 'Fashion',
        description: 'Ukuran S. Pemakaian 1 tahun, dijual karena salah ukuran.',
        location: 'Surabaya',
        stock: 3
    },
    {
        id: '10',
        name: 'Hoodie Pria Terbaru',
        price: 262500,
        originalPrice: 350000,
        discount: 25,
        condition: 'Good',
        image: 'https://ryusei.co.id/cdn/shop/files/Artboard1_4b32a791-ac00-45d4-ae2f-2d9437c72f3d.png?v=1718953696',
        images: [
            'https://ryusei.co.id/cdn/shop/files/Artboard1_4b32a791-ac00-45d4-ae2f-2d9437c72f3d.png?v=1718953696',
        ],
        rating: 4.8,
        reviewCount: 20,
        seller: {
            id: 's10',
            name: 'Ryusei',
            avatar: 'https://placehold.co/100x100',
            rating: 4.5,
            responseTime: '< 1 hour',
            totalSales: 520,
            verified: true
        },
        isPremium: true,
        category: 'Fashion',
        description: 'Ukuran M. Pemakaian 1 tahun, dijual karena salah ukuran.',
        location: 'Surabaya',
        stock: 2
    },
    {
        id: '11',
        name: 'Kursi Kerja Kantor Minimalis',
        price: 2000000,
        originalPrice: 2500000,
        discount: 20,
        condition: 'Good',
        image: 'https://img.lazcdn.com/g/p/3f4c5fe0b9e042ad537a3f38bbff72c6.jpg_720x720q80.jpg',
        images: [
            'https://img.lazcdn.com/g/p/3f4c5fe0b9e042ad537a3f38bbff72c6.jpg_720x720q80.jpg',
        ],
        rating: 4.8,
        reviewCount: 100,
        seller: {
            id: 's11',
            name: 'Baby Shop 22',
            avatar: 'https://placehold.co/100x100',
            rating: 4.5,
            responseTime: '< 1 hour',
            totalSales: 89,
            verified: false
        },
        isPremium: true,
        category: 'Furniture',
        description: 'Kursi Kerja Kursi Kantor Minimalis Dengan Roda. Sandaran tangan tegap',
        location: 'Surabaya',
        stock: 1
    },
    {
        id: '12',
        name: 'Meja Belajar MB GL 982',
        price: 502500,
        originalPrice: 602500,
        discount: 17,
        condition: 'Good',
        image: 'https://inverio.co.id/wp-content/uploads/2022/01/Meja-Belajar-MB-GL-982.png',
        images: [
            'https://inverio.co.id/wp-content/uploads/2022/01/Meja-Belajar-MB-GL-982.png',
        ],
        rating: 4.8,
        reviewCount: 100,
        seller: {
            id: 's12',
            name: 'INVERIO',
            avatar: 'https://placehold.co/100x100',
            rating: 4.5,
            responseTime: '< 1 hour',
            totalSales: 210,
            verified: true
        },
        isPremium: true,
        category: 'Furniture',
        description: 'Manufacturer : Grace. ColorSonoma : Oak. FinishingLapis : Paper. Materials : Kayu Olahan Particle Board',
        location: 'Surabaya',
        stock: 1
    },
    {
        id: '13',
        name: 'Stora 68x35x70 Cm Rak Sepatu 3 Tingkat - Hitam',
        price: 132000,
        originalPrice: 150000,
        discount: 12,
        condition: 'Good',
        image: 'https://cdn.ruparupa.io/fit-in/850x850/filters:format(webp)/filters:watermark(content.ruparupa.io,products/wm/rr.png,0,-0,0,100,100)/ruparupa-com/image/upload/Products/10182428_1.jpg',
        images: [
            'https://cdn.ruparupa.io/fit-in/850x850/filters:format(webp)/filters:watermark(content.ruparupa.io,products/wm/rr.png,0,-0,0,100,100)/ruparupa-com/image/upload/Products/10182428_1.jpg',
        ],
        rating: 5,
        reviewCount: 50,
        seller: {
            id: 's13',
            name: 'INVERIO',
            avatar: 'https://placehold.co/100x100',
            rating: 4.5,
            responseTime: '< 1 hour',
            totalSales: 210,
            verified: true
        },
        isPremium: false,
        category: 'Furniture',
        description: 'Material berkualitas tinggi. Instalasi mudah',
        location: 'Surabaya',
        stock: 5
    },
    {
        id: '14',
        name: 'Metode Penelitian Kuantitatif Kualitatif Dan R&D karya Prof. Sugiyono',
        price: 106000,
        originalPrice: 150000,
        discount: 12,
        condition: 'Good',
        image: 'https://cdn.gramedia.com/uploads/picture_meta/2023/3/8/exqptqpg5zwe5zttmuxv7u.jpg',
        images: [
            'https://cdn.gramedia.com/uploads/picture_meta/2023/3/8/exqptqpg5zwe5zttmuxv7u.jpg',
        ],
        rating: 5,
        reviewCount: 50,
        seller: {
            id: 's14',
            name: 'Alfabeta',
            avatar: 'https://placehold.co/100x100',
            rating: 5,
            responseTime: '< 1 hour',
            totalSales: 890,
            verified: true
        },
        isPremium: false,
        category: 'Books',
        description: 'Metode Penelitian Kuantitatif Kualitatif Dan R&D Karya Prof. Dr. Sugiyono adalah buku yang berisi hal-hal yang berkaitan dengan penelitian.',
        location: 'Surabaya',
        stock: 10
    },
    {
        id: '15',
        name: 'TARMAK Bola Basket BT900 Ukuran 7 Disetujui FIBA',
        price: 649000,
        originalPrice: 700000,
        discount: 7,
        condition: 'Good',
        image: 'https://contents.mediadecathlon.com/p2705092/k$34bfd1a1787dcb27067366160c047e32/bola-basket-bt900-ukuran-7-disetujui-fiba-tarmak-8648080.jpg?f=1920x0&format=auto',
        images: [
            'https://contents.mediadecathlon.com/p2705092/k$34bfd1a1787dcb27067366160c047e32/bola-basket-bt900-ukuran-7-disetujui-fiba-tarmak-8648080.jpg?f=1920x0&format=auto',
        ],
        rating: 5,
        reviewCount: 50,
        seller: {
            id: 's15',
            name: 'Decathlon',
            avatar: 'https://placehold.co/100x100',
            rating: 5,
            responseTime: '< 1 hour',
            totalSales: 1500,
            verified: true
        },
        isPremium: false,
        category: 'Sports',
        description: 'Bola basket ukuran 7 cocok untuk anak laki-laki usia di atas 13 tahun.',
        location: 'Surabaya',
        stock: 3
    },
    {
        id: '16',
        name: 'Vas Bunga Gerabah Spayol',
        price: 322000,
        originalPrice: 600000,
        discount: 45,
        condition: 'Good',
        image: 'https://ntbmall.com/images/product/a90864be-2725-421f-bef0-f7ee141475ad/a90864be-2725-421f-bef0-f7ee141475ad-12022-02-18%2015:05:12.png',
        images: [
            'https://ntbmall.com/images/product/a90864be-2725-421f-bef0-f7ee141475ad/a90864be-2725-421f-bef0-f7ee141475ad-12022-02-18%2015:05:12.png',
        ],
        rating: 5,
        reviewCount: 50,
        seller: {
            id: 's16',
            name: 'Alfabeta',
            avatar: 'https://placehold.co/100x100',
            rating: 5,
            responseTime: '< 1 hour',
            totalSales: 890,
            verified: true
        },
        isPremium: false,
        category: 'Home & Garden',
        description: 'Vas bunga yang terbuat dari gerabah tanah liat Desa Banyuurip.',
        location: 'Surabaya',
        stock: 2
    }
]

export const categories = [
    { id: 'all', name: 'Semua', icon: '🏠' },
    { id: 'electronics', name: 'Elektronik', icon: '📱' },
    { id: 'fashion', name: 'Fashion', icon: '👕' },
    { id: 'furniture', name: 'Furniture', icon: '🪑' },
    { id: 'books', name: 'Buku', icon: '📚' },
    { id: 'sports', name: 'Olahraga', icon: '⚽' },
    { id: 'home', name: 'Rumah & Taman', icon: '🌿' },
]

export const paymentMethods = [
    { id: 'bca', name: 'BCA Virtual Account', type: 'bank', icon: '🏦' },
    { id: 'bni', name: 'BNI Virtual Account', type: 'bank', icon: '🏦' },
    { id: 'mandiri', name: 'Mandiri Virtual Account', type: 'bank', icon: '🏦' },
    { id: 'gopay', name: 'GoPay', type: 'ewallet', icon: '💳' },
    { id: 'ovo', name: 'OVO', type: 'ewallet', icon: '💳' },
    { id: 'dana', name: 'DANA', type: 'ewallet', icon: '💳' },
    { id: 'cod', name: 'Bayar di Tempat (COD)', type: 'cod', icon: '🚚' },
]
